/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pjpl.simaticscada.form;

/**
 *
 * @author piotr
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form manFrame
	 */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cbx_I_0 = new javax.swing.JCheckBox();
    cbx_I_2 = new javax.swing.JCheckBox();
    cbx_I_1 = new javax.swing.JCheckBox();
    cbx_I_3 = new javax.swing.JCheckBox();
    cbx_I_4 = new javax.swing.JCheckBox();
    cbx_I_5 = new javax.swing.JCheckBox();
    cbx_I_6 = new javax.swing.JCheckBox();
    cbx_I_7 = new javax.swing.JCheckBox();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    cbx_Q_0 = new javax.swing.JCheckBox();
    cbx_Q_1 = new javax.swing.JCheckBox();
    cbx_Q_2 = new javax.swing.JCheckBox();
    cbx_Q_3 = new javax.swing.JCheckBox();
    cbx_Q_4 = new javax.swing.JCheckBox();
    cbx_Q_5 = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("scadaFrama"); // NOI18N

    cbx_I_0.setText("wejście 0");
    cbx_I_0.setEnabled(false);
    cbx_I_0.setName("cbx_I_0"); // NOI18N

    cbx_I_2.setText("wejście 2");
    cbx_I_2.setEnabled(false);
    cbx_I_2.setName("cbx_I_2"); // NOI18N

    cbx_I_1.setText("wejście 1");
    cbx_I_1.setEnabled(false);
    cbx_I_1.setName("cbx_I_1"); // NOI18N
    cbx_I_1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbx_I_1ActionPerformed(evt);
      }
    });

    cbx_I_3.setText("wejście 3");
    cbx_I_3.setEnabled(false);
    cbx_I_3.setName("cbx_I_3"); // NOI18N

    cbx_I_4.setText("wejście 4");
    cbx_I_4.setEnabled(false);
    cbx_I_4.setName("cbx_I_4"); // NOI18N

    cbx_I_5.setText("wejście 5");
    cbx_I_5.setEnabled(false);

    cbx_I_6.setText("wejście 6");
    cbx_I_6.setEnabled(false);

    cbx_I_7.setText("wejście 7");
    cbx_I_7.setEnabled(false);

    jTextField1.setToolTipText("");
    jTextField1.setName("tfByte"); // NOI18N
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    jLabel1.setText("zmienna Byte");

    jLabel2.setText("zmienna    Int");

    jLabel3.setText("zmienna DInt");

    jLabel4.setText("zmienna Byte");

    jTextField2.setAutoscrolls(false);
    jTextField2.setName("tfInt"); // NOI18N
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField2ActionPerformed(evt);
      }
    });

    jTextField3.setToolTipText("");
    jTextField3.setName("tfDInt"); // NOI18N
    jTextField3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField3ActionPerformed(evt);
      }
    });

    jTextField4.setToolTipText("");
    jTextField4.setName("tfReal"); // NOI18N
    jTextField4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField4ActionPerformed(evt);
      }
    });

    cbx_Q_0.setText("wyjście 0");
    cbx_Q_0.setToolTipText("");
    cbx_Q_0.setName("cbx_Q_0"); // NOI18N

    cbx_Q_1.setText("wyjście 2");
    cbx_Q_1.setToolTipText("");
    cbx_Q_1.setName("cbx_Q_2"); // NOI18N

    cbx_Q_2.setText("wyjście 1");
    cbx_Q_2.setToolTipText("");
    cbx_Q_2.setName("cbx_Q_1"); // NOI18N

    cbx_Q_3.setText("wyjście 3");
    cbx_Q_3.setToolTipText("");
    cbx_Q_3.setName("cbx_Q_3"); // NOI18N

    cbx_Q_4.setText("wyjście 4");
    cbx_Q_4.setToolTipText("");
    cbx_Q_4.setName("cbx_Q_4"); // NOI18N

    cbx_Q_5.setText("wyjście 5");
    cbx_Q_5.setToolTipText("");
    cbx_Q_5.setName("cbx_Q_5"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cbx_I_0)
              .addComponent(cbx_I_1)
              .addComponent(cbx_I_2, javax.swing.GroupLayout.Alignment.TRAILING))
            .addComponent(cbx_I_3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(cbx_I_4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(cbx_I_5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(cbx_I_6, javax.swing.GroupLayout.Alignment.TRAILING))
          .addComponent(cbx_I_7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                  .addGap(1, 1, 1)
                  .addComponent(jLabel2))
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
              .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField3)
              .addComponent(jTextField1)
              .addComponent(jTextField2)
              .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cbx_Q_2, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(cbx_Q_0, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(cbx_Q_1, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(cbx_Q_3, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(cbx_Q_4, javax.swing.GroupLayout.Alignment.TRAILING)))
          .addComponent(cbx_Q_5, javax.swing.GroupLayout.Alignment.TRAILING))
        .addGap(84, 84, 84))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cbx_Q_0)
              .addComponent(jLabel1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel4)))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Q_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Q_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Q_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Q_4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_Q_5))
          .addGroup(layout.createSequentialGroup()
            .addComponent(cbx_I_0)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbx_I_7)))
        .addContainerGap(102, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cbx_I_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_I_1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cbx_I_1ActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField2ActionPerformed

  private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField3ActionPerformed

  private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField4ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox cbx_I_0;
  private javax.swing.JCheckBox cbx_I_1;
  private javax.swing.JCheckBox cbx_I_2;
  private javax.swing.JCheckBox cbx_I_3;
  private javax.swing.JCheckBox cbx_I_4;
  private javax.swing.JCheckBox cbx_I_5;
  private javax.swing.JCheckBox cbx_I_6;
  private javax.swing.JCheckBox cbx_I_7;
  private javax.swing.JCheckBox cbx_Q_0;
  private javax.swing.JCheckBox cbx_Q_1;
  private javax.swing.JCheckBox cbx_Q_2;
  private javax.swing.JCheckBox cbx_Q_3;
  private javax.swing.JCheckBox cbx_Q_4;
  private javax.swing.JCheckBox cbx_Q_5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables
}
